-- Supabase auto-enables RLS on new tables via rls_auto_enable().
-- Disable RLS on tables outside this phase scope (admin_users and review_log only).

ALTER TABLE accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE affirmation_tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE affirmations DISABLE ROW LEVEL SECURITY;
ALTER TABLE card_likes DISABLE ROW LEVEL SECURITY;
ALTER TABLE card_related_overrides DISABLE ROW LEVEL SECURITY;
ALTER TABLE card_tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE cards DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE content_blocks DISABLE ROW LEVEL SECURITY;
ALTER TABLE favorites DISABLE ROW LEVEL SECURITY;
ALTER TABLE newsletter_subscriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE push_subscriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE quotes DISABLE ROW LEVEL SECURITY;
ALTER TABLE recovery_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE reported_issues DISABLE ROW LEVEL SECURITY;
ALTER TABLE sources DISABLE ROW LEVEL SECURITY;
ALTER TABLE submissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE tags DISABLE ROW LEVEL SECURITY;

REVOKE EXECUTE ON FUNCTION is_admin_user() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION current_admin_user_id() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION is_admin_user() TO authenticated;
GRANT EXECUTE ON FUNCTION current_admin_user_id() TO authenticated;
